services:
  - type: postgres
    name: form-visa-db
    plan: starter
    region: sao-paulo
    databaseName: back_production
    envVars:
      - key: POSTGRES_USER
        value: your_db_user
      - key: POSTGRES_PASSWORD
        value: your_db_password
      - key: POSTGRES_DB
        value: back_production
    # Render vai gerar DATABASE_URL automaticamente

  - type: web
    name: form-visa-back
    env: ruby
    region: sao-paulo
    branch: main
    rootDir: back
    buildCommand: bundle install
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: form-visa-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        value: your_rails_master_key
      - key: JWT_SECRET
        value: some_secure_random_key
      - key: FRONTEND_FORM_URL
        value: https://form-visa-front.onrender.com
      - key: ASAAS_WEBHOOK_TOKEN
        value: your_asaas_token
    autoDeploy: true
    preDeployCommand: bundle exec rails db:migrate

  - type: web
    name: form-visa-front
    env: node
    region: sao-paulo
    branch: main
    rootDir: front
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://form-visa-back.onrender.com/api
    autoDeploy: true